# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenvectors_sparse <- function(X, n_vec) {
    .Call('_lighthergm_eigenvectors_sparse', PACKAGE = 'lighthergm', X, n_vec)
}

#' Compute Yule's Φ-coefficient
#' @param z_star a true block membership
#' @param z an estimated block membership
#' @export
compute_yule_coef <- function(z_star, z) {
    .Call('_lighthergm_compute_yule_coef', PACKAGE = 'lighthergm', z_star, z)
}

get_sparse_feature_adjmat <- function(x) {
    .Call('_lighthergm_get_sparse_feature_adjmat', PACKAGE = 'lighthergm', x)
}

get_sparse_feature_adjmat_from_string <- function(x) {
    .Call('_lighthergm_get_sparse_feature_adjmat_from_string', PACKAGE = 'lighthergm', x)
}

get_matrix_for_denominator <- function(numOfVertices, list_feature_adjmat) {
    .Call('_lighthergm_get_matrix_for_denominator', PACKAGE = 'lighthergm', numOfVertices, list_feature_adjmat)
}

get_elementwise_multiplied_matrices <- function(adjmat, list_feature_adjmat) {
    .Call('_lighthergm_get_elementwise_multiplied_matrices', PACKAGE = 'lighthergm', adjmat, list_feature_adjmat)
}

decimal_to_binary_vector <- function(decimal, vec_length) {
    .Call('_lighthergm_decimal_to_binary_vector', PACKAGE = 'lighthergm', decimal, vec_length)
}

compute_sumTaus <- function(numOfVertices, numOfClasses, tau, verbose = 0L) {
    .Call('_lighthergm_compute_sumTaus', PACKAGE = 'lighthergm', numOfVertices, numOfClasses, tau, verbose)
}

compute_quadratic_term_naive <- function(numOfVertices, numOfClasses, pi, tau, network) {
    .Call('_lighthergm_compute_quadratic_term_naive', PACKAGE = 'lighthergm', numOfVertices, numOfClasses, pi, tau, network)
}

compute_linear_term <- function(numOfVertices, numOfClasses, alpha, tau, LB) {
    .Call('_lighthergm_compute_linear_term', PACKAGE = 'lighthergm', numOfVertices, numOfClasses, alpha, tau, LB)
}

compute_pi <- function(numOfVertices, numOfClasses, stat, tau) {
    .Call('_lighthergm_compute_pi', PACKAGE = 'lighthergm', numOfVertices, numOfClasses, stat, tau)
}

compute_quadratic_term <- function(numOfVertices, numOfClasses, alpha, tau, network, LB, verbose = 0L) {
    .Call('_lighthergm_compute_quadratic_term', PACKAGE = 'lighthergm', numOfVertices, numOfClasses, alpha, tau, network, LB, verbose)
}

run_EM_without_features <- function(numOfVertices, numOfClasses, alpha, tau, network, verbose = 0L) {
    .Call('_lighthergm_run_EM_without_features', PACKAGE = 'lighthergm', numOfVertices, numOfClasses, alpha, tau, network, verbose)
}

compute_denominator_for_pi_d1x0 <- function(numOfVertices, numOfClasses, matrix_for_denominator, tau, verbose) {
    .Call('_lighthergm_compute_denominator_for_pi_d1x0', PACKAGE = 'lighthergm', numOfVertices, numOfClasses, matrix_for_denominator, tau, verbose)
}

compute_pi_d1x0 <- function(numOfVertices, numOfClasses, list_multiplied_feature_adjmat, tau, verbose) {
    .Call('_lighthergm_compute_pi_d1x0', PACKAGE = 'lighthergm', numOfVertices, numOfClasses, list_multiplied_feature_adjmat, tau, verbose)
}

compute_quadratic_term_with_features <- function(numOfVertices, numOfClasses, list_multiplied_feature_adjmat, tau, LB, verbose = 0L) {
    .Call('_lighthergm_compute_quadratic_term_with_features', PACKAGE = 'lighthergm', numOfVertices, numOfClasses, list_multiplied_feature_adjmat, tau, LB, verbose)
}

compute_pi_with_features <- function(numOfVertices, numOfClasses, list_multiplied_feature_adjmat, tau) {
    .Call('_lighthergm_compute_pi_with_features', PACKAGE = 'lighthergm', numOfVertices, numOfClasses, list_multiplied_feature_adjmat, tau)
}

run_EM_with_features <- function(numOfVertices, numOfClasses, alpha, list_multiplied_feature_adjmat, tau, verbose = 0L) {
    .Call('_lighthergm_run_EM_with_features', PACKAGE = 'lighthergm', numOfVertices, numOfClasses, alpha, list_multiplied_feature_adjmat, tau, verbose)
}

simulate_between_network <- function(numOfVertices, list_feature_adjmat, coef_between, block_membership, directed) {
    .Call('_lighthergm_simulate_between_network', PACKAGE = 'lighthergm', numOfVertices, list_feature_adjmat, coef_between, block_membership, directed)
}

